route:
  receiver: "telegram & mail alert"
  group_by: ["alertname", "cluster"]
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1h
receivers:
  - name: "telegram & mail alert"
    telegram_configs:
      - bot_token_file: /etc/alertmanager/bot_token.txt
        chat_id: 942008903
        send_resolved: true
        message: "(╥﹏╥) High Disk Usage (╥﹏╥)"

    email_configs:
      - to: "kyrollesraafat@gmail.com"
        from: "kyrollesraafat99@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "kyrollesraafat99@gmail.com"
        auth_password_file: /etc/alertmanager/auth_e.txt
        headers:
          subject: "Prometheus Mail Alerts"
        send_resolved: true
